use serde::{Deserialize, Serialize};
/// =================================
/// 配置类(模型)
/// =================================
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    pub default_model: String,
    pub temperature: f64,
    pub max_tokens: Option<usize>,
    pub context_window: usize,
    pub compression_threshold: f64,
    pub min_retain_rounds: usize,
    pub enable_smart_compression: bool,
    pub summary_llm_provider: String,
    pub summary_llm_model: String,
    pub summary_max_tokens: usize,
    pub summary_temperature: f64,
    pub tool_output_max_lines: usize,
    pub tool_output_max_bytes: usize,
    pub tool_output_dir: String,
    pub tool_output_truncate_direction: String,
    pub trace_enabled: bool,
    pub trace_dir: String,
    pub trace_sanitize: bool,
    pub trace_html_include_raw_response: bool,
    pub skills_enabled: bool,
    pub skills_dir: String,
    pub skills_auto_register: bool,
    pub circuit_enabled: bool,
    pub circuit_failure_threshold: usize,
    pub circuit_recovery_timeout: usize,
    pub session_enabled: bool,
    pub session_dir: String,
    pub auto_save_enabled: bool,
    pub auto_save_interval: usize,
    pub subagent_enabled: bool,
    pub subagent_max_steps: usize,
    pub subagent_use_light_llm: bool,
    pub subagent_light_llm_provider: String,
    pub subagent_light_llm_model: String,
    pub todowrite_enabled: bool,
    pub todowrite_persistence_dir: String,
    pub devlog_enabled: bool,
    pub devlog_persistence_dir: String,
    pub async_enabled: bool,
    pub max_concurrent_tools: usize,
    pub hook_timeout_seconds: f64,
    pub llm_async_timeout: usize,
    pub tool_async_timeout: usize,
    pub stream_enabled: bool,
    pub stream_buffer_size: usize,
    pub stream_include_thinking: bool,
    pub stream_include_tool_calls: bool,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            default_model: "deepseek-v4-flash".into(),
            temperature: 0.7,
            max_tokens: None,
            context_window: 128000,
            compression_threshold: 0.8,
            min_retain_rounds: 10,
            enable_smart_compression: false,
            summary_llm_provider: "deepseek".into(),
            summary_llm_model: "deepseek-chat".into(),
            summary_max_tokens: 800,
            summary_temperature: 0.3,
            tool_output_max_lines: 2000,
            tool_output_max_bytes: 51200,
            tool_output_dir: "tool-output".into(),
            tool_output_truncate_direction: "head".into(),
            trace_enabled: true,
            trace_dir: "memory/traces".into(),
            trace_sanitize: true,
            trace_html_include_raw_response: false,
            skills_enabled: true,
            skills_dir: "skills".into(),
            skills_auto_register: true,
            circuit_enabled: true,
            circuit_failure_threshold: 3,
            circuit_recovery_timeout: 300,
            session_enabled: true,
            session_dir: "memory/sessions".into(),
            auto_save_enabled: false,
            auto_save_interval: 10,
            subagent_enabled: true,
            subagent_max_steps: 15,
            subagent_use_light_llm: false,
            subagent_light_llm_provider: "deepseek".into(),
            subagent_light_llm_model: "deepseek-chat".into(),
            todowrite_enabled: true,
            todowrite_persistence_dir: "memory/todos".into(),
            devlog_enabled: true,
            devlog_persistence_dir: "memory/devlogs".into(),
            async_enabled: true,
            max_concurrent_tools: 3,
            hook_timeout_seconds: 5.0,
            llm_async_timeout: 120,
            tool_async_timeout: 30,
            stream_enabled: true,
            stream_buffer_size: 100,
            stream_include_thinking: true,
            stream_include_tool_calls: true,
        }
    }
}
