//! tool_base.rs
//! 工具基类 - Rust 实现，通过 struct + trait 组合实现抽象类和 AutoGeneratedTool

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Instant;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use serde_json::Value;

// 依赖项目内已有类型
use crate::core::exceptions::HelloAgentException;
use crate::tools::tool_error::ToolErrorCode;
use crate::tools::tool_response::ToolResponse;

// ------------------------------------------------------------
// 私有辅助函数（替代原 trait 中的 insert_value / merge_context）
// ------------------------------------------------------------

fn insert_value(target: &mut Option<Value>, key: &str, value: Value) {
    if let Some(ref mut v) = target {
        if let Value::Object(ref mut map) = v {
            map.insert(key.to_string(), value);
        }
    } else {
        let mut map = serde_json::Map::new();
        map.insert(key.to_string(), value);
        *target = Some(Value::Object(map));
    }
}

fn merge_context(target: &mut Option<Value>, extra: serde_json::Map<String, Value>) {
    if let Some(ref mut v) = target {
        if let Value::Object(ref mut map) = v {
            for (k, val) in extra {
                map.insert(k, val);
            }
        }
    } else {
        *target = Some(Value::Object(extra));
    }
}

// ------------------------------------------------------------
// ToolParameter
// ------------------------------------------------------------

/// 工具参数定义
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolParameter {
    pub name: String,
    #[serde(rename = "type")]
    pub param_type: String,
    pub description: String,
    pub required: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default: Option<Value>,
}

impl ToolParameter {
    pub fn new(
        name: impl Into<String>,
        param_type: impl Into<String>,
        description: impl Into<String>,
        required: bool,
        default: Option<Value>,
    ) -> Self {
        Self {
            name: name.into(),
            param_type: param_type.into(),
            description: description.into(),
            required,
            default,
        }
    }
}

// ------------------------------------------------------------
// ToolBase - 工具公共数据和方法（组合复用）
// ------------------------------------------------------------

/// 工具基础信息，被具体工具 struct 持有
#[derive(Debug, Clone)]
pub struct ToolBase {
    pub name: String,
    pub description: String,
    pub expandable: bool,
}

impl ToolBase {
    pub fn new(name: impl Into<String>, description: impl Into<String>, expandable: bool) -> Self {
        Self {
            name: name.into(),
            description: description.into(),
            expandable,
        }
    }

    /// 验证参数（需要参数列表）
    pub fn validate_parameters(&self, parameters: &Value, required_params: &[String]) -> bool {
        if let Value::Object(map) = parameters {
            required_params.iter().all(|key| map.contains_key(key))
        } else {
            false
        }
    }

    /// 转换为字典（需要参数列表）
    pub fn to_dict(&self, params: &[ToolParameter]) -> HashMap<String, Value> {
        let mut dict = HashMap::new();
        dict.insert("name".to_string(), Value::String(self.name.clone()));
        dict.insert("description".to_string(), Value::String(self.description.clone()));
        let param_values: Vec<Value> = params
            .iter()
            .map(|p| serde_json::to_value(p).unwrap_or_default())
            .collect();
        dict.insert("parameters".to_string(), Value::Array(param_values));
        dict
    }

    /// 转换为 OpenAI function calling schema（需要参数列表）
    pub fn to_openai_schema(&self, params: &[ToolParameter]) -> Value {
        let mut properties = serde_json::Map::new();
        let mut required = Vec::new();

        for param in params {
            let mut prop = serde_json::Map::new();
            prop.insert("type".to_string(), Value::String(param.param_type.clone()));
            let mut desc = param.description.clone();
            if let Some(default) = &param.default {
                desc = format!("{} (默认: {})", desc, default);
            }
            prop.insert("description".to_string(), Value::String(desc));

            if param.param_type == "array" {
                prop.insert("items".to_string(), serde_json::json!({"type": "string"}));
            }
            properties.insert(param.name.clone(), Value::Object(prop));

            if param.required {
                required.push(Value::String(param.name.clone()));
            }
        }

        serde_json::json!({
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": properties,
                    "required": required
                }
            }
        })
    }
}

// ------------------------------------------------------------
// Tool trait - 工具接口，提供默认实现
// ------------------------------------------------------------
/// - 新协议版本
///
///     支持两种使用模式：
///     1. 普通模式：工具作为单一实体使用
///     2. 可展开模式：工具可以展开为多个独立的子工具（每个子工具对应一个功能）
///
///     展开模式支持两种实现方式：
///     - 手动定义子工具类（传统方式）
///     - 使用 @tool_action 装饰器自动生成（推荐）
///
///     新协议特性：
///     - run() 方法返回 ToolResponse 对象（而非字符串）
///     - 提供 run_with_timing() 自动添加时间统计
///     - 支持结构化的状态、数据和错误信息
#[async_trait]
pub trait Tool: Send + Sync {
    /// 工具名称
    fn name(&self) -> &str;
    /// 返回工具基础信息（不可变引用）
    fn base(&self) -> &ToolBase;
    /// 返回工具基础信息（可变引用）
    fn base_mut(&mut self) -> &mut ToolBase;

    /// 执行工具（抽象方法）
    fn run(&self, parameters: Value) -> Result<ToolResponse, HelloAgentException>;

    /// 获取工具参数定义（抽象方法）
    fn get_parameters(&self) -> Vec<ToolParameter>;

    /// 克隆自身为 Box<dyn Tool>（用于展开子工具等场景）
    fn box_clone(&self) -> Box<dyn Tool>;

    /// 是否可展开
    fn is_expandable(&self) -> bool {
        self.base().expandable
    }

    /// 收集所有通过装饰器或手动注册的子工具（默认空）
    /// 子类可重写此方法来提供子工具列表
    fn get_tool_actions(&self) -> Vec<Box<dyn Tool>> {
        vec![]
    }

    /// 获取展开后的子工具列表
    /// 默认实现：检查 expandable，若为 true 则调用 get_tool_actions() 获取列表，
    /// 若非空则返回 Some，否则返回 None。
    fn get_expanded_tools(&self) -> Option<Vec<Box<dyn Tool>>> {
        if !self.is_expandable() {
            return None;
        }
        let tools = self.get_tool_actions();
        if tools.is_empty() {
            None
        } else {
            Some(tools)
        }
    }

    /// 同步执行并添加时间统计和上下文信息
    fn run_with_timing(&self, parameters: Value) -> ToolResponse {
        let start = Instant::now();
        let result = self.run(parameters.clone());
        let elapsed_ms = start.elapsed().as_millis() as u64;

        match result {
            Ok(mut response) => {
                insert_value(&mut response.stats, "time_ms", serde_json::Number::from(elapsed_ms).into());
                let mut ctx_map = serde_json::Map::new();
                ctx_map.insert("params_input".to_string(), parameters);
                ctx_map.insert("tool_name".to_string(), Value::String(self.name().to_string()));
                merge_context(&mut response.context, ctx_map);
                response
            }
            Err(e) => {
                ToolResponse::error(
                    ToolErrorCode::InternalError.as_str(),
                    &format!("工具执行时发生未处理的异常: {}", e),
                    Some(serde_json::json!({ "time_ms": elapsed_ms })),
                    Some(serde_json::json!({
                        "params_input": parameters,
                        "tool_name": self.name()
                    })),
                )
            }
        }
    }

    /// 异步执行工具（默认实现：在线程池中运行同步 run）
    async fn arun(&self, parameters: Value) -> Result<ToolResponse, HelloAgentException> {
        let tool_clone = self.box_clone();
        let params = parameters.clone();
        tokio::task::spawn_blocking(move || tool_clone.run(params))
            .await
            .map_err(|e| HelloAgentException::ToolException(format!("异步任务失败: {}", e)))?
    }

    /// 异步执行并添加时间统计
    async fn arun_with_timing(&self, parameters: Value) -> ToolResponse {
        let start = Instant::now();
        let result = self.arun(parameters.clone()).await;
        let elapsed_ms = start.elapsed().as_millis() as u64;

        match result {
            Ok(mut response) => {
                insert_value(&mut response.stats, "time_ms", serde_json::Number::from(elapsed_ms).into());
                let mut ctx_map = serde_json::Map::new();
                ctx_map.insert("params_input".to_string(), parameters);
                ctx_map.insert("tool_name".to_string(), Value::String(self.name().to_string()));
                merge_context(&mut response.context, ctx_map);
                response
            }
            Err(e) => {
                ToolResponse::error(
                    ToolErrorCode::InternalError.as_str(),
                    &format!("异步工具执行异常: {}", e),
                    Some(serde_json::json!({ "time_ms": elapsed_ms })),
                    Some(serde_json::json!({
                        "params_input": parameters,
                        "tool_name": self.name()
                    })),
                )
            }
        }
    }

    /// 验证参数
    fn validate_parameters(&self, parameters: &Value) -> bool {
        let required: Vec<String> = self
            .get_parameters()
            .iter()
            .filter(|p| p.required)
            .map(|p| p.name.clone())
            .collect();
        self.base().validate_parameters(parameters, &required)
    }

    /// 转为字典
    fn to_dict(&self) -> HashMap<String, Value> {
        let params = self.get_parameters();
        self.base().to_dict(&params)
    }

    /// 转为 OpenAI schema
    fn to_openai_schema(&self) -> Value {
        let params = self.get_parameters();
        self.base().to_openai_schema(&params)
    }
}

// ------------------------------------------------------------
// AutoGeneratedTool - 自动生成的工具（对应 Python 的 AutoGeneratedTool）
// ------------------------------------------------------------

pub struct AutoGeneratedTool {
    base: ToolBase,
    parameters: Vec<ToolParameter>,
    executor: Arc<dyn Fn(Value) -> Result<ToolResponse, HelloAgentException> + Send + Sync>,
}

impl AutoGeneratedTool {
    pub fn new(
        name: impl Into<String>,
        description: impl Into<String>,
        parameters: Vec<ToolParameter>,
        executor: impl Fn(Value) -> Result<ToolResponse, HelloAgentException> + Send + Sync + 'static,
    ) -> Self {
        Self {
            base: ToolBase::new(name, description, false),
            parameters,
            executor: Arc::new(executor),
        }
    }

    pub fn with_base(mut self, base: ToolBase) -> Self {
        self.base = base;
        self
    }
}

impl Tool for AutoGeneratedTool {
    fn name(&self) -> &str {
        &self.base.name
    }
    fn base(&self) -> &ToolBase {
        &self.base
    }
    fn base_mut(&mut self) -> &mut ToolBase {
        &mut self.base
    }
    fn run(&self, parameters: Value) -> Result<ToolResponse, HelloAgentException> {
        (self.executor)(parameters)
    }
    fn get_parameters(&self) -> Vec<ToolParameter> {
        self.parameters.clone()
    }
    fn box_clone(&self) -> Box<dyn Tool> {
        Box::new(Self {
            base: self.base.clone(),
            parameters: self.parameters.clone(),
            executor: Arc::clone(&self.executor),
        })
    }
}

// ------------------------------------------------------------
// 测试用例
// ------------------------------------------------------------
#[cfg(test)]
mod tests {
    use super::*;
    use crate::tools::tool_response::ToolStatus;
    use serde_json::json;

    // 示例 EchoTool 实现，组合 ToolBase
    #[derive(Clone)]
    struct EchoTool {
        base: ToolBase,
        parameters: Vec<ToolParameter>,
    }

    impl EchoTool {
        fn new() -> Self {
            Self {
                base: ToolBase::new("echo", "回显输入", false),
                parameters: vec![ToolParameter::new(
                    "input",
                    "string",
                    "需要回显的文本",
                    true,
                    None,
                )],
            }
        }
    }

    impl Tool for EchoTool {
        fn name(&self) -> &str {
            &self.base.name
        }
        fn base(&self) -> &ToolBase {
            &self.base
        }
        fn base_mut(&mut self) -> &mut ToolBase {
            &mut self.base
        }
        fn run(&self, parameters: Value) -> Result<ToolResponse, HelloAgentException> {
            let input = parameters["input"].as_str().unwrap_or("");
            Ok(ToolResponse::success(
                input,
                Some(json!({"echoed": input})),
                None,
                None,
            ))
        }
        fn get_parameters(&self) -> Vec<ToolParameter> {
            self.parameters.clone()
        }
        fn box_clone(&self) -> Box<dyn Tool> {
            Box::new(self.clone())
        }
    }

    // 一个可展开的工具，通过 get_tool_actions 提供子工具
    struct ExpandableTool {
        base: ToolBase,
    }

    impl ExpandableTool {
        fn new() -> Self {
            Self {
                base: ToolBase::new("exp", "可展开工具", true),
            }
        }
    }

    impl Tool for ExpandableTool {
        fn name(&self) -> &str {
            &self.base.name
        }
        fn base(&self) -> &ToolBase {
            &self.base
        }
        fn base_mut(&mut self) -> &mut ToolBase {
            &mut self.base
        }
        fn run(&self, _: Value) -> Result<ToolResponse, HelloAgentException> {
            Ok(ToolResponse::success("expanded", None, None, None))
        }
        fn get_parameters(&self) -> Vec<ToolParameter> {
            vec![]
        }
        fn box_clone(&self) -> Box<dyn Tool> {
            Box::new(Self {
                base: self.base.clone(),
            })
        }
        /// 覆盖此方法以提供子工具，相当于 Python 中重写 get_expanded_tools
        fn get_tool_actions(&self) -> Vec<Box<dyn Tool>> {
            vec![Box::new(EchoTool::new())]
        }
    }

    #[test]
    fn test_run_with_timing_success() {
        let tool = EchoTool::new();
        let resp = tool.run_with_timing(json!({"input": "hello"}));
        assert_eq!(resp.status, ToolStatus::Success);
        assert!(resp.stats.as_ref().unwrap().get("time_ms").is_some());
        let ctx = resp.context.as_ref().unwrap();
        assert_eq!(ctx["tool_name"], "echo");
        assert_eq!(ctx["params_input"]["input"], "hello");
    }

    #[test]
    fn test_run_with_error_converts_to_error_response() {
        struct FailTool {
            base: ToolBase,
        }
        impl FailTool {
            fn new() -> Self {
                Self {
                    base: ToolBase::new("fail", "always fail", false),
                }
            }
        }
        impl Tool for FailTool {
            fn name(&self) -> &str { &self.base.name }
            fn base(&self) -> &ToolBase { &self.base }
            fn base_mut(&mut self) -> &mut ToolBase { &mut self.base }
            fn run(&self, _: Value) -> Result<ToolResponse, HelloAgentException> {
                Err(HelloAgentException::ToolException("simulated failure".into()))
            }
            fn get_parameters(&self) -> Vec<ToolParameter> { vec![] }
            fn box_clone(&self) -> Box<dyn Tool> {
                Box::new(Self { base: self.base.clone() })
            }
        }

        let tool = FailTool::new();
        let resp = tool.run_with_timing(json!({}));
        assert_eq!(resp.status, ToolStatus::Error);
        let err = resp.error_info.as_ref().unwrap();
        assert_eq!(err.code, ToolErrorCode::InternalError.as_str());
        assert!(err.message.contains("simulated failure"));
    }

    #[test]
    fn test_validate_parameters() {
        let tool = EchoTool::new();
        assert!(tool.validate_parameters(&json!({"input": "test"})));
        assert!(!tool.validate_parameters(&json!({"wrong": "x"})));
    }

    #[test]
    fn test_to_openai_schema() {
        let tool = EchoTool::new();
        let schema = tool.to_openai_schema();
        assert_eq!(schema["type"], "function");
        let func = &schema["function"];
        assert_eq!(func["name"], "echo");
        assert!(func["parameters"]["required"]
            .as_array()
            .unwrap()
            .contains(&Value::String("input".into())));
    }

    #[test]
    fn test_get_expanded_tools() {
        let tool = ExpandableTool::new();
        let expanded = tool.get_expanded_tools();
        assert!(expanded.is_some());
        let tools = expanded.unwrap();
        assert_eq!(tools.len(), 1);
        assert_eq!(tools[0].name(), "echo");
    }

    #[test]
    fn test_auto_generated_tool() {
        let tool = AutoGeneratedTool::new(
            "my_tool",
            "a test tool",
            vec![ToolParameter::new("x", "integer", "x value", true, None)],
            |args| {
                let x = args["x"].as_i64().unwrap_or(0);
                Ok(ToolResponse::success(
                    format!("result: {}", x * 2),
                    Some(json!({"doubled": x * 2})),
                    None,
                    None,
                ))
            },
        );

        let resp = tool.run_with_timing(json!({"x": 5}));
        assert_eq!(resp.status, ToolStatus::Success);
        assert_eq!(resp.text, "result: 10");
    }

    #[tokio::test]
    async fn test_arun_with_timing() {
        let tool = EchoTool::new();
        let resp = tool.arun_with_timing(json!({"input": "async test"})).await;
        assert_eq!(resp.status, ToolStatus::Success);
        assert!(resp.stats.as_ref().unwrap().get("time_ms").is_some());
        assert_eq!(resp.text, "async test");
    }
}